### ISSUE TITLE
[Request] Add support for model YLYTD-0003

### ISSUE THREAD

**Issue by jahirfiquitiva** [kyuuri10010/homebridge-yeelight-screen-light-bar#1]
https://www.amazon.com/dp/B09GB33N7C

**Comment by kyuuri10010** [comment]
@jahirfiquitiva 
I don't have YLYTD-0003, so could you tell me the Model information that you can check with the Yeelight app?

Information can be found on the screen below.
Yeelight app > Your device > Setting > Device Info > Model

![IMG_6518](https://user-images.githubusercontent.com/68772225/187361143-eac3fac9-8f44-48e5-b036-2f95f86c3e86.PNG)

**Comment by jahirfiquitiva** [comment]
@kyuuri10010 it shows the exact same model

**Comment by kyuuri10010** [comment]
@jahirfiquitiva 
If the same model is shown, I think that "YLYTD-0003" can also be used with the currently published version.

**Comment by jahirfiquitiva** [comment]
@kyuuri10010 it shows "Not supported model" as error 😕

**Comment by kyuuri10010** [comment]
@jahirfiquitiva 
The model information that can be obtained with the API may be different.
I have published "1.0.3-beta.1" that outputs the model obtained by the API to the log.
Can you check the model information with this?

**Comment by jahirfiquitiva** [comment]
@kyuuri10010 how can i install such version? i don't see that option in homebridge

**Comment by kyuuri10010** [comment]
@jahirfiquitiva 
You can install by specifying the version.
`npm i -g homebridge-yeelight-screen-light-bar@1.0.3-beta.1`

If you are using "Homebridge Config UI X", you can install it by specifying the version from the list on the Plugins page.

![screenshot](https://user-images.githubusercontent.com/68772225/187826435-fa5549fd-49f1-4587-87fa-4e60dfc4f77e.png)

**Comment by jahirfiquitiva** [comment]
thanks @kyuuri10010 it is now working properly 😄
